=== isonovio/wyndis-archive/data/schemas/player.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "nickname", "nationalities"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "nickname": { "type": "string" },
        "name": { "type": "string" },
        "birthday": { "type": "string", "format": "date" },
        "nationalities": { "type": "array", "items": { "$ref": "nationality.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "#/$defs/tag" } },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } }
    },

    "$defs": {
        "tag": {
            "type": "string",
            "enum": ["twin", "ninja", "impact", "coach"]
        }
    }
}

=== isonovio/wyndis-archive/data/twins/players/d0cc.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "d0cc",
    "nickname": "D0cC",
    "name": "Shuaib Ahmad",
    "birthday": "2000-09-04",
    "nationalities": ["nl", "pk"],
    "links": [
        { "name": "d0cc", "url": "https://d0cc.gg/" },
        { "name": "ESEA", "url": "https://play.esea.net/users/D0cC%5E" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/D0cC" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/18361/d0cc" },
        { "name": "Instagram", "url": "https://www.instagram.com/d0cc_csgo" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/D0cC" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/OfficialD0cC/" },
        { "name": "Twitch", "url": "https://www.twitch.tv/d0cc_tv" },
        { "name": "Twitter", "url": "https://x.com/D0cC_csgo" },
        { "name": "YouTube", "url": "https://www.youtube.com/@D0cCTV" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/tiggz.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "tiggz",
    "nickname": "Tiggz",
    "name": "Sabrina van Bommel",
    "nationalities": ["nl"],
    "tags": ["impact"],
    "links": [
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/Tiggzzz" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/1960/tiggz" },
        { "name": "Twitter", "url": "https://x.com/tiggztv" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/mackdaddy.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "mackdaddy",
    "nickname": "MackDaddy",
    "name": "Marcus Eriksson Gonzalez",
    "nationalities": ["se"],
    "birthday": "1996-01-30",
    "tags": ["coach"],
    "links": [
        { "name": "ESEA", "url": "https://play.esea.net/users/941332" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/MackDaddy" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/19067/mackdaddy" },
        { "name": "Instagram", "url": "https://www.instagram.com/marcus.sseg" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/MackDaddy" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/MackDaddyo/" },
        { "name": "Twitch", "url": "https://www.twitch.tv/MackDaddy0" },
        { "name": "Twitter", "url": "https://x.com/MackDaddyCS" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/rookie.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "rookie",
    "nickname": "Rookie",
    "name": "Pierre Haladjian",
    "nationalities": ["lb"],
    "tags": ["coach"],
    "links": [
        { "name": "HLTV", "url": "https://www.hltv.org/player/11401/rookie" },
        { "name": "Twitch", "url": "https://www.twitch.tv/ro0kie_tv" },
        { "name": "Twitter", "url": "https://x.com/ro0kie_tv" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/carnem.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "carnem",
    "nickname": "CARNEM",
    "name": "Jakob Sommer",
    "nationalities": ["dk"],
    "tags": ["coach"],
    "links": [
        { "name": "HLTV", "url": "https://www.hltv.org/coach/23139/carnem" },
        { "name": "Twitter", "url": "https://x.com/CARNEM9" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/nayay.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "nayay",
    "nickname": "nayay",
    "name": "Naja Block Bach",
    "birthday": "1998-08-27",
    "nationalities": ["dk"],
    "tags": ["impact"],
    "links": [
        { "name": "HLTV", "url": "https://www.hltv.org/player/22651/nayay" },
        { "name": "Twitter", "url": "https://x.com/nayaycs" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/qiyarah.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "qiyarah",
    "nickname": "Qiyarah",
    "name": "Kiara Janssen",
    "birthday": "2003-11-05",
    "nationalities": ["nl"],
    "tags": ["twin", "ninja", "impact"],
    "links": [
        { "name": "ESEA", "url": "https://play.esea.net/users/2528275" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/Qiyarah" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/21796/qiyarah" },
        { "name": "Instagram", "url": "https://www.instagram.com/qiyarah.cs" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/Qiyarah" },
        { "name": "Pinterest", "url": "https://www.pinterest.com/qiyarahgg/" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/Qiyarah/" },
        { "name": "TikTok", "url": "https://www.tiktok.com/@qiyarahcs" },
        { "name": "Twitch", "url": "https://www.twitch.tv/Qiyarah" },
        { "name": "Twitter", "url": "https://x.com/Qiyarahcs" },
        { "name": "YouTube", "url": "https://www.youtube.com/@Qiyarahcs" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/eneshan.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "eneshan",
    "nickname": "eneshan",
    "name": "Eneshan Tez",
    "birthday": "2000-04-26",
    "nationalities": ["nl", "tr"],
    "links": [
        { "name": "ESEA", "url": "https://play.esea.net/users/1865450" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/eneshan" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/19066/eneshan" },
        { "name": "Instagram", "url": "https://www.instagram.com/eneshancsgo" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/Eneshan" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/eneshan1473/" },
        { "name": "TikTok", "url": "https://www.tiktok.com/@eneshancsgo" },
        { "name": "Twitch", "url": "https://www.twitch.tv/eneshancsgo" },
        { "name": "Twitter", "url": "https://x.com/eneshancsgo" },
        { "name": "YouTube", "url": "https://www.youtube.com/@eneshancsgo" }
    ]
}
