=== isonovio/wyndis-archive/data/schemas/player.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "nickname", "nationalities"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "nickname": { "type": "string" },
        "name": { "type": "string" },
        "birthday": { "type": "string", "format": "date" },
        "nationalities": { "type": "array", "items": { "$ref": "nationality.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "#/$defs/tag" } },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } }
    },

    "$defs": {
        "tag": {
            "type": "string",
            "enum": ["twin", "ninja", "impact", "coach"]
        }
    }
}

=== isonovio/wyndis-archive/data/twins/players/kniven.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "kniven",
    "nickname": "kniven",
    "nationalities": [],
    "links": [
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/kniven" },
        { "name": "Instagram", "url": "https://www.instagram.com/knivencs/" },
        { "name": "Twitch", "url": "https://www.twitch.tv/kniven" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/regretfully/" }
    ]
}
