=== isonovio/wyndis-archive/data/schemas/talent.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "nickname"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "nickname": { "type": "string" },
        "name": { "type": "string" },
        "birthday": { "type": "string", "format": "date" },
        "nationalities": { "type": "array", "items": { "$ref": "nationality.schema.json" } },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } }
    }
}

=== isonovio/wyndis-archive/data/twins/players/litmus.json
{
    "$schema": "../../schemas/talent.schema.json",
    "slug": "litmus",
    "nickname": "Litmus",
    "nationalities": ["gb"],
    "links": [
        { "name": "Steam", "url": "https://steamcommunity.com/id/Litmusq" },
        { "name": "Twitch", "url": "https://x.com/Litmusq" },
        { "name": "Twitter", "url": "https://x.com/Litmusq" },
        { "name": "YouTube", "url": "https://www.youtube.com/@Litmusq" }
    ]
}
